#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="residualStressFoam"
rm -r 0
cp -r 0.org 0

runApplication $application
